services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: car_angular_container
    ports:
      - "4201:4200"
    volumes:
      - ./:/home/node/app
    environment:
      - TZ=America/Sao_Paulo
