/**
 * Formas de pagamento aceitas em uma venda.
 * Reflete o enum FormaPagamento.java do Backend.
 */
export enum FormaPagamento {
  DINHEIRO = 'DINHEIRO',
  PIX = 'PIX',
  BOLETO = 'BOLETO',
  FINANCIAMENTO = 'FINANCIAMENTO',
  CHEQUE = 'CHEQUE',
  TED = 'TED',
  DOC = 'DOC',
  CARTAO_CREDITO = 'CARTAO_CREDITO',
  CARTAO_DEBITO = 'CARTAO_DEBITO',
  CREDITO_LOJA = 'CREDITO_LOJA',
  VALE_ALIMENTACAO = 'VALE_ALIMENTACAO',
  VALE_REFEICAO = 'VALE_REFEICAO',
  VALE_PRESENTE = 'VALE_PRESENTE',
  VALE_COMBUSTIVEL = 'VALE_COMBUSTIVEL',
  DUPLICATA_MERCANTIL = 'DUPLICATA_MERCANTIL',
  SEM_PAGAMENTO = 'SEM_PAGAMENTO',
  TROCA = 'TROCA',
  PROMISSORIA = 'PROMISSORIA',
  OUTROS = 'OUTROS',
}
