export enum VehicleType {
  AUTOMOVEL = 'AUTOMOVEL',
  MOTOCICLETA = 'MOTOCICLETA',
  CAMINHONETE = 'CAMINHONETE',
  CAMIONETA = 'CAMIONETA',
  CAMINHAO = 'CAMINHAO',
  ONIBUS = 'ONIBUS',
  REBOQUE = 'REBOQUE',
}
