name: Deploy CAR Front-end

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Building Angular project
        run: npm run build

      - name: Login Docker hub
        # run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build docker image
        run: docker build -t tkdcris/car-frontend:latest .

      - name: Push image docker
        run: docker push tkdcris/car-frontend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull tkdcris/car-frontend:latest

      - name: Remove docker container
        # run: docker rm -f car-frontend
        run: |
          docker stop car-frontend || true
          docker rm car-frontend || true

      - name: Remove older image
        run: docker rmi $(docker images -q tkdcris/car-frontend) || true

      - name: Run docker container
        run: docker run -d -p 80:80 --name car-frontend tkdcris/car-frontend:latest
